### ISSUE TITLE
Question about the "Rho baseline" in paper

### ISSUE THREAD

**Issue by HaebinShin** [GAIR-NLP/ProX#8]
Thanks for your amazing work!
I'd like ask about the baseline (**"1.1B RHO"** in Table) in your [paper](https://arxiv.org/pdf/2409.17115)

I'm curious whether the "1.1B Rho" performance reported in this paper is a reproduced result or the original result.
This is because there's a huge performance gap compared to the Rho paper, which I assume is due to using different reference models (the Rho paper uses GPT-4 as the reference model).

- In Rho paper:
![image](https://github.com/user-attachments/assets/308f967b-7c1a-4799-91e1-7b76d9736620)

- In ProX paper:
![image](https://github.com/user-attachments/assets/14974f9f-6b35-4e9d-9eb7-427f5fca8877)

Given this, I’m guessing that the "1.1B Rho" in Table 5 refers to the reproduced performance using the ProX curated data. 
Is that correct?

If then, what reference model was used in Table 5? Is it TinyLlama that was continually pretrained on ProX?

Thanks!

**Comment by koalazf99** [comment]
Hi @HaebinShin , Thanks for your interest!

Here, we report RHO-1's best self-reference results, which should reported in Table 3 of Rho paper.

<img width="885" alt="image" src="https://github.com/user-attachments/assets/05c5b0a1-d8b0-4f50-b017-46c86f5f60bc">

As you mentioned,  Rho-1-Math-1.1B actually use much larger reference models which have been trained on downstream tasks, so we decide it is not very similar to ProX's experiment settings.

**Comment by HaebinShin** [comment]
Oh, It was OWM self-reference model results. Got it. 
I agree that it should be compared with the OWM version's reference model, as you mentioned.
Thanks for the quick response!
